name = "svelte-cloudflare-template"
account_id = "d8ee18029fb3e06794971d45b9c4a67d"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]
assets = { binding = "ASSETS", directory = ".svelte-kit/cloudflare" }

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "template-database"
database_id = "10f70983-c171-4c14-83fa-0fe991fb430e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "template-bucket"

[[kv_namespaces]]
binding = "kv"
id = "9fb337a9b93f459ab54640ad251aee01"
